# Generated by Django 4.0.3 on 2022-04-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=250)),
                ('Companyname', models.CharField(max_length=250)),
                ('companyaddress', models.CharField(max_length=250)),
                ('jobdescription', models.CharField(max_length=500)),
                ('qulification', models.CharField(max_length=250)),
                ('responsibility', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('comapanywebsite', models.CharField(max_length=250)),
                ('Companyemail', models.CharField(max_length=250)),
                ('companycontact', models.CharField(max_length=20)),
                ('salarypachage', models.CharField(max_length=250)),
                ('exprience', models.IntegerField()),
                ('logo', models.ImageField(default='', upload_to='app/img/jobpost')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
